services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 src/modules/bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8174756157:AAGECPZ3ctcaGE86EQVfpnoR3v8zUqdvtxA

